const state={player:null,cities:[],city:null,activity:null,view:'city'};
const $=id=>document.getElementById(id); const fmt=n=>Number(n??0).toLocaleString();
async function request(url,opts={}){const r=await fetch(url,opts);if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
async function get(url){const r=await fetch(url);if(!r.ok)throw new Error(await r.text());return r.json()}
function showNotice(msg){$('notice').textContent=msg;$('notice').classList.remove('hidden');setTimeout(()=>$('notice').classList.add('hidden'),2600)}
function renderHUD(){const c=state.city,p=state.player;$('cityName').textContent=c.name;$('coords').textContent=`(${c.coordinates.x}, ${c.coordinates.y})`;$('gold').textContent=fmt(c.economy.gold);$('population').textContent=`${fmt(c.population.total)} / ${fmt(c.population.idle)} idle`;$('prestige').textContent=fmt(p.prestige);$('resources').innerHTML=c.resources.map(r=>`<div class="resource"><span>${r.kind[0].toUpperCase()+r.kind.slice(1)}</span><b>${fmt(r.quantity)}</b><small>+${fmt(r.production_per_hour)}/h · cap ${fmt(r.capacity)}</small></div>`).join('');$('civicStatus').innerHTML=`<span>Tax ${c.economy.tax_rate}%</span><span>Loyalty ${c.economy.loyalty}</span><span>Grievance ${c.economy.grievance}</span><span>Honor ${fmt(p.honor)}</span>${p.title_rank_key?`<span>Title ${p.title_rank_key}</span>`:''}`;renderActivity()}
function renderActivity(){const a=state.activity;const rows=[];for(const q of a.construction)rows.push(`Construction → Lv.${q.target_level} · ${q.status}`);for(const q of a.research)rows.push(`Research ${q.technology_key} → Lv.${q.target_level} · ${q.status}`);for(const q of a.training)rows.push(`Training ${fmt(q.quantity)} ${q.troop_type_key} · ${q.status}`);for(const q of a.marches)rows.push(`${q.mission} → (${q.target.x},${q.target.y}) · ${q.status}`);$('activityRows').innerHTML=rows.length?rows.map(x=>`<span class="op">${x}</span>`).join(''):'<span class="op empty">No active construction, research, training, or marches.</span>'}
function plotHTML(p,field=false){if(field&&p.locked)return `<div class="plot locked" data-plot="${p.plot_index}"><span class="plot-index">Plot ${p.plot_index}</span><span class="symbol">🔒</span><strong>Locked Field</strong><small>Upgrade Town Hall to unlock</small></div>`;if(!p.building)return `<div class="plot empty" data-plot="${p.plot_index}"><span class="plot-index">Plot ${p.plot_index}</span><span class="symbol">${field?'⌁':'◇'}</span><strong>Empty Plot</strong><small>${field?'Click to choose Farm, Sawmill, Quarry, or Iron Mine':'Click to construct'}</small></div>`;return `<div class="plot ${p.building.dedicated?'dedicated':''}" data-plot="${p.plot_index}"><span class="plot-index">${p.building.dedicated?'Dedicated':`Plot ${p.plot_index}`}</span><span class="symbol">▦</span><strong>${p.building.definition_key.replaceAll('_',' ')}</strong><small>Level ${p.building.level}${p.building.level===0?' · constructing':''}</small></div>`}
async function loadView(){const base=`/api/players/${state.player.id}/cities/${state.city.id}`;if(state.view==='city'){const d=await get(base+'/city-view');$('cityPlots').innerHTML=d.plots.map(p=>plotHTML(p)).join('');document.querySelectorAll('#cityPlots .plot').forEach(el=>el.addEventListener('click',()=>handleCityPlot(d.plots.find(p=>p.plot_index===Number(el.dataset.plot))).catch(e=>showNotice(e.message))))}else if(state.view==='fields'){const d=await get(base+'/field-view');const p=d.production;$('fieldPlots').innerHTML=`<div class="field-summary"><b>Resource Fields:</b> ${d.available_plots}/37 unlocked · <b>Population:</b> ${fmt(p.population)} · <b>Assigned:</b> ${fmt(Math.round(p.assigned_labor))} · <b>Idle:</b> ${fmt(p.idle_population)}<br>${Object.entries(p.resources).map(([k,v])=>`${k}: ${fmt(Math.round(v.effective_per_hour))}/hr · ${v.production_percent}%`).join(' · ')}<br><b>Production items:</b> ${Object.entries(d.production_items).flatMap(([kind,items])=>Object.entries(items).map(([key,spec])=>`<button class="prod-item-btn" data-key="${key}" ${(d.inventory[key]||0)>0?'':'disabled'}>${key.replaceAll('_',' ')} +${spec.percent}% (${fmt(d.inventory[key]||0)})</button>`)).join(' ')}</div>`+[...d.plots,...d.locked_plots].map(x=>plotHTML(x,true)).join('');const all=[...d.plots,...d.locked_plots];document.querySelectorAll('#fieldPlots .plot').forEach(el=>el.addEventListener('click',()=>handleFieldPlot(all.find(x=>x.plot_index===Number(el.dataset.plot))).catch(e=>showNotice(e.message))));document.querySelectorAll('.prod-item-btn').forEach(b=>b.onclick=async()=>{try{await post(base+'/production-item',{item_key:b.dataset.key,idempotency_key:crypto.randomUUID()});await loadView();renderHUD();showNotice('Production item applied.')}catch(e){showNotice(e.message)}})}else await loadMap()}
const mapState={x:null,y:null,radius:6,loading:false};
function clampMap(v){return Math.max(0,Math.min(799,Number(v)||0))}
async function centerMap(x,y){mapState.x=clampMap(x);mapState.y=clampMap(y);await loadMap()}
async function loadMap(){
 if(mapState.loading)return;mapState.loading=true;
 try{
  if(mapState.x===null){mapState.x=state.city.coordinates.x;mapState.y=state.city.coordinates.y}
  const d=await get(`/api/map?player_id=${state.player.id}&center_x=${mapState.x}&center_y=${mapState.y}&radius=${mapState.radius}`);
  mapState.x=d.center.x;mapState.y=d.center.y;$('mapCenter').textContent=`Current coordinate: (${mapState.x}, ${mapState.y})`;$('mapX').value=mapState.x;$('mapY').value=mapState.y;
  $('mapGrid').style.setProperty('--map-cols',d.width);const marchText=(d.marches||[]).map(m=>`#${m.id} ${m.mission} ${m.status} → ${m.destination.x},${m.destination.y} (${m.seconds_remaining??0}s)`).join(' · ');$('mapCenter').textContent+=marchText?` | ${marchText}`:'';
  $('mapGrid').innerHTML=d.tiles.map(t=>{let cls='',sym='·',label='Open land';if(t.tile_type==='PLAYER_CITY'){cls='city';sym='◆';label=t.name||'City'}else if(t.tile_type==='NPC_CITY'){cls='npc';sym='▣';label=`NPC ${t.level}`}else if(t.tile_type==='VALLEY'){cls='valley';sym='▲';label=`${t.valley_type||'Valley'} ${t.level}`}else if(t.tile_type==='FLAT'){cls='flat';sym='◇';label=`Flat ${t.level}`};return `<div class="tile ${cls} ${t.x===mapState.x&&t.y===mapState.y?'center':''}" data-x="${t.x}" data-y="${t.y}"><button class="map-tile-hitbox" data-x="${t.x}" data-y="${t.y}" aria-label="${esc(label)} at ${t.x},${t.y}"></button><div class="tile-content"><b>${sym}</b><span>${esc(label)}</span><small>${t.x},${t.y}</small></div></div>`}).join('');
  document.querySelectorAll('.map-tile-hitbox').forEach(el=>el.onclick=()=>openMapTile(+el.dataset.x,+el.dataset.y));
  await loadBookmarks();
 }finally{mapState.loading=false}
}
async function openMapTile(x,y){
 const t=await get(`/api/map/tile/${x}/${y}?player_id=${state.player.id}`);let extra='';
 if(t.tile_type==='VALLEY'||t.tile_type==='FLAT'){
  try{const w=await get(`/api/players/${state.player.id}/map/wilderness/${x}/${y}`);extra=`<p>${w.valley_type?`Type: ${esc(w.valley_type)} · `:''}${w.bonus&&w.bonus.percent?`${esc(w.bonus.resource)} +${w.bonus.percent}%`:w.kind==='FLAT'?'No production bonus':''}</p><p>${w.owner_name?`Owned by ${esc(w.owner_name)}`:'Unowned'} · Defenders ${w.defenders_present?'present':'cleared'}</p>`}catch(_){}
 }
 const actions=(t.actions||[]).map(a=>`<button class="action-btn map-action" data-a="${a}">${a}</button>`).join('');
 $('modalBody').innerHTML=`<div class="building-panel"><h2>${esc(t.tile_type.replaceAll('_',' '))} (${t.x}, ${t.y})</h2>${t.name?`<p>${esc(t.name)}${t.owner_name?' — '+esc(t.owner_name):''}</p>`:''}${t.level!==null?`<p>Level ${t.level}</p>`:''}${extra}<p>${actions||'No available action.'}</p>${(t.tile_type==='VALLEY'||t.tile_type==='FLAT')?'<button id="tileScout" class="action-btn">Scout</button> ':''}${t.occupied_by_city_id===state.city.id?'<button id="tileAbandon" class="action-btn">Abandon</button> ':''}${t.tile_type==='FLAT'&&t.occupied_by_city_id===state.city.id?'<button id="tileBuildCity" class="action-btn">Build City</button> ':''}<button id="tileCenter" class="action-btn">Center map here</button></div>`;$('buildingModal').classList.remove('hidden');$('tileCenter').onclick=async()=>{await centerMap(t.x,t.y);$('buildingModal').classList.add('hidden')};
 if($('tileScout'))$('tileScout').onclick=async()=>{try{const r=await post(`/api/players/${state.player.id}/map/wilderness/${x}/${y}/scout`,{city_id:state.city.id,idempotency_key:crypto.randomUUID()});showNotice(`Scout: ${JSON.stringify(r.defenders)}`)}catch(e){showNotice(e.message)}};
 if($('tileAbandon'))$('tileAbandon').onclick=async()=>{try{await post(`/api/players/${state.player.id}/map/wilderness/${x}/${y}/abandon`,{city_id:state.city.id,idempotency_key:crypto.randomUUID()});await loadMap();$('buildingModal').classList.add('hidden')}catch(e){showNotice(e.message)}};
 if($('tileBuildCity'))$('tileBuildCity').onclick=async()=>{const name=prompt('New city name','New City');if(!name)return;try{await post(`/api/players/${state.player.id}/map/flats/${x}/${y}/build-city`,{source_city_id:state.city.id,name,idempotency_key:crypto.randomUUID()});showNotice('City founded.');location.reload()}catch(e){showNotice(e.message)}};
 document.querySelectorAll('.map-action').forEach(b=>b.onclick=()=>showNotice(`${b.dataset.a} uses the Rally Spot/march interface; tile target is (${t.x},${t.y}).`));
}
async function loadBookmarks(){
 const d=await get(`/api/players/${state.player.id}/map/bookmarks`);
 $('mapBookmarks').innerHTML=d.bookmarks.length?d.bookmarks.map(b=>`<div class="bookmark-row"><button class="action-btn bookmark-jump" data-x="${b.x}" data-y="${b.y}">${esc(b.label)} (${b.x},${b.y})</button><button class="action-btn bookmark-delete" data-id="${b.id}">Delete</button></div>`).join(''):'<p>No bookmarks.</p>';
 document.querySelectorAll('.bookmark-jump').forEach(b=>b.onclick=()=>centerMap(+b.dataset.x,+b.dataset.y));
 document.querySelectorAll('.bookmark-delete').forEach(b=>b.onclick=async()=>{try{await request(`/api/players/${state.player.id}/map/bookmarks/${b.dataset.id}?idempotency_key=${encodeURIComponent(crypto.randomUUID())}`,{method:'DELETE'});await loadBookmarks()}catch(e){showNotice(e.message)}});
}
function wireMapControls(){
 $('mapHome').onclick=()=>centerMap(state.city.coordinates.x,state.city.coordinates.y);$('mapGo').onclick=()=>centerMap($('mapX').value,$('mapY').value);
 $('mapLeft').onclick=()=>centerMap(mapState.x-1,mapState.y);$('mapRight').onclick=()=>centerMap(mapState.x+1,mapState.y);$('mapUp').onclick=()=>centerMap(mapState.x,mapState.y-1);$('mapDown').onclick=()=>centerMap(mapState.x,mapState.y+1);
 $('mapBookmark').onclick=async()=>{try{await post(`/api/players/${state.player.id}/map/bookmarks`,{x:mapState.x,y:mapState.y,label:$('bookmarkLabel').value||null,idempotency_key:crypto.randomUUID()});$('bookmarkLabel').value='';await loadBookmarks()}catch(e){showNotice(e.message)}};
 const shell=document.querySelector('.map-shell');let sx=0,sy=0; if(shell){shell.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY});shell.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<45)return;if(Math.abs(dx)>Math.abs(dy))centerMap(mapState.x+(dx<0?1:-1),mapState.y);else centerMap(mapState.x,mapState.y+(dy<0?1:-1))})}
}

async function selectCity(id){const d=await get(`/api/players/${state.player.id}/cities/${id}/overview`);state.city=d.city;state.cityId=d.city.id;state.activity=d.activity;state.player=d.player;state.playerId=d.player.id;renderHUD();refreshBeginnerProtection();await loadView()}
function switchView(view){state.view=view;document.querySelectorAll('.game-view').forEach(x=>x.classList.add('hidden'));$(`${view}View`).classList.remove('hidden');document.querySelectorAll('.view-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));loadView().catch(e=>showNotice('Server view unavailable: '+e.message))}
async function init(){try{const d=await get('/api/development/session');state.player=d.player;state.playerId=d.player.id;state.cities=d.cities;state.city=d.current_city;state.cityId=d.current_city.id;state.activity=d.activity;$('citySelect').innerHTML=d.cities.map(c=>`<option value="${c.id}">${c.name} (${c.x},${c.y})</option>`).join('');$('citySelect').value=state.city.id;$('citySelect').addEventListener('change',e=>selectCity(e.target.value));document.querySelectorAll('.view-tabs button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));renderHUD();wireMapControls();await loadView();try{await get('/api/dev/status');$('economyDebugButton').classList.remove('hidden');$('economyDebugButton').onclick=openEconomyDebug}catch(_){}}catch(e){showNotice('Unable to load authoritative game state.');console.error(e)}}init();

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function duration(s){if(s==='HISTORICAL_VALUE_UNKNOWN')return s;const m=Math.floor(s/60),sec=s%60;return m?`${m}m ${sec}s`:`${sec}s`}
function closeModal(){$('buildingModal').classList.add('hidden')}
$('modalClose').addEventListener('click',closeModal);$('buildingModal').addEventListener('click',e=>{if(e.target===$('buildingModal'))closeModal()})
async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){let t=await r.text();try{t=JSON.parse(t).detail}catch{}throw new Error(t)}return r.json()}
async function openEmptyPlot(plot){const d=await get(`/api/players/${state.player.id}/cities/${state.city.id}/construction-options`);$('modalBody').innerHTML=`<h2>Construct Building — Plot ${plot.plot_index}</h2><p>All currently evaluated in-town building definitions are shown. Unknown historical tables are not guessed.</p><div class="build-list">${d.options.map(o=>{const costs=typeof o.cost==='object'?Object.entries(o.cost).map(([k,v])=>`<span>${esc(k)} ${fmt(v)}</span>`).join(''):'<span>HISTORICAL_VALUE_UNKNOWN</span>';const req=o.unmet_requirements.length?o.unmet_requirements.map(esc).join(' · '):'Requirements met';return `<div class="build-option"><h3>${esc(o.name)}</h3><p>${esc(o.purpose)}</p><div class="costs">${costs}<span>Time ${esc(duration(o.construction_seconds))}</span></div><div class="requirements">${req}</div><button class="action-btn construct-btn" data-key="${esc(o.key)}" ${o.available?'':'disabled'}>Construct</button></div>`}).join('')}</div>`;$('buildingModal').classList.remove('hidden');document.querySelectorAll('.construct-btn').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/construct`,{plot_index:plot.plot_index,building_key:b.dataset.key,idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('Construction started on authoritative server.')}catch(e){b.disabled=false;showNotice(e.message)}}))}
async function openBuilding(building){const d=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);let fn='';if(d.function.type==='population')fn=`Population ${fmt(d.function.population)} · Idle ${fmt(d.function.idle_population)}`;else if(d.function.type==='training')fn=`Troops: ${d.function.troops.map(t=>`${esc(t.type)} ${fmt(t.quantity)}`).join(', ')||'none'}<br><span class="unfinished">${esc(d.function.training)}</span>`;else fn=`<span class="unfinished">${esc(d.function.status||d.function.recruitment||'')}</span>`;const up=typeof d.upgrade==='object'?`Cost ${Object.entries(d.upgrade.cost).map(([k,v])=>`${esc(k)} ${fmt(v)}`).join(' · ')} · Time ${duration(d.upgrade.seconds)}`:'HISTORICAL_VALUE_UNKNOWN';$('modalBody').innerHTML=`<div class="building-panel"><h2>${esc(d.name)} — Level ${d.level}</h2><p>${esc(d.purpose)}</p><div class="function-box">${fn}</div><h3>Upgrade</h3><p>${up}</p><button id="upgradeBtn" class="action-btn" ${typeof d.upgrade==='object'?'':'disabled'}>Upgrade to Level ${d.level+1}</button><h3>Demolish / Downgrade</h3><p class="unfinished">${esc(d.demolition.labor)}</p><p class="unfinished">${esc(d.demolition.dynamite)}</p></div>`;$('buildingModal').classList.remove('hidden');const u=$('upgradeBtn');if(u&&!u.disabled)u.addEventListener('click',async()=>{u.disabled=true;try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${d.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('Upgrade started on authoritative server.')}catch(e){u.disabled=false;showNotice(e.message)}})}
async function handleCityPlot(plot){if(plot.building)await openBuilding(plot.building);else await openEmptyPlot(plot)}
async function openTownHall(){
 const base=`/api/players/${state.player.id}/cities/${state.city.id}/town-hall`,d=await get(base),u=d.upgrade;
 const cost=u?Object.entries(u.cost).map(([k,v])=>`${esc(k)} ${fmt(v)}`).join(' · '):'Maximum configured normal level';
 const prereq=!u?'':(u.prerequisites==='HISTORICAL_VALUE_UNKNOWN'?'HISTORICAL_VALUE_UNKNOWN':(u.prerequisites.length?u.prerequisites.map(x=>`${x.building} Lv.${x.level}`).join(', '):'None'));
 $('modalBody').innerHTML=`<div class="building-panel town-hall-panel"><h2>Town Hall — Level ${d.level}</h2><p>Permanent dedicated city administration structure.</p><div class="function-box"><b>Resource fields:</b> ${d.resource_fields.available} available · <b>Valley limit:</b> ${d.valley_limit}<br><b>Population:</b> ${fmt(d.population.total)} · <b>Idle:</b> ${fmt(d.population.idle)}<br><b>Gold:</b> ${fmt(d.public_state.gold)} · <b>Tax:</b> ${d.public_state.tax_rate}% · <b>Loyalty:</b> ${d.public_state.loyalty} · <b>Grievance:</b> ${d.public_state.grievance}</div>
 <h3>Production</h3><div class="th-grid">${['food','lumber','stone','iron'].map(k=>`<label>${k}<input class="prod-input" data-kind="${k}" type="number" min="0" max="100" value="${d.production_rates[k]??100}">%</label>`).join('')}</div><button id="saveProduction" class="action-btn">Set Production</button><p>Production is calculated authoritatively from server timestamps and the city’s field, labor, technology, Mayor, valley and active item modifiers.</p>
 <h3>Tax Rate</h3><label>Tax <input id="taxInput" type="number" min="0" max="100" value="${d.public_state.tax_rate}">%</label> <button id="saveTax" class="action-btn">Set Tax Rate</button>
 <h3>Rename City</h3><input id="renameInput" value="${esc(state.city.name)}"> <button id="saveRename" class="action-btn">Rename</button>
 <h3>Comforting</h3><select id="comfortAction"><option value="disaster_relief">Disaster Relief</option><option value="praying">Praying</option><option value="blessing">Blessing</option><option value="population_raising">Population Raising</option></select> <button id="comfortBtn" class="action-btn">Apply</button><h3>Levy</h3><select id="levyAction"><option value="gold">Gold</option><option value="food">Food</option><option value="lumber">Lumber</option><option value="stone">Stone</option><option value="iron">Iron</option></select> <button id="levyBtn" class="action-btn">Levy</button>
 <h3>Upgrade</h3><p>${u?`To Level ${u.target_level} · ${cost} · Time ${duration(u.seconds)} · Prerequisites: ${esc(prereq)}`:'Level 10 is the maximum configured normal Town Hall level.'}</p>${u&&Object.keys(u.item_cost).length?`<p>Items: ${Object.entries(u.item_cost).map(([k,v])=>`${esc(k)} × ${v}`).join(' · ')}</p>`:''}<button id="thUpgrade" class="action-btn" ${u&&u.can_start?'':'disabled'}>${u?'Upgrade Town Hall':'Maximum Level'}</button>${u&&!u.can_start?'<p class="unfinished">Upgrade disabled because exact historical prerequisite data is unresolved.</p>':''}</div>`;
 $('buildingModal').classList.remove('hidden');
 $('saveTax').onclick=async()=>{try{await post(base+'/tax',{tax_rate:Number($('taxInput').value),idempotency_key:crypto.randomUUID()});await selectCity(state.city.id);showNotice('Tax rate updated.')}catch(e){showNotice(e.message)}};
 $('saveRename').onclick=async()=>{try{await post(base+'/rename',{name:$('renameInput').value,idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('City renamed.')}catch(e){showNotice(e.message)}};
 $('saveProduction').onclick=async()=>{const body={idempotency_key:crypto.randomUUID()};document.querySelectorAll('.prod-input').forEach(x=>body[x.dataset.kind]=Number(x.value));try{await post(base+'/production',body);showNotice('Production controls updated.')}catch(e){showNotice(e.message)}};
 $('comfortBtn').onclick=async()=>{try{await post(base+'/comfort',{action:$('comfortAction').value,idempotency_key:crypto.randomUUID()});await selectCity(state.city.id);showNotice('Comforting applied.')}catch(e){showNotice(e.message)}};
 $('levyBtn').onclick=async()=>{try{await post(base+'/levy',{action:$('levyAction').value,idempotency_key:crypto.randomUUID()});await selectCity(state.city.id);showNotice('Levy enacted.')}catch(e){showNotice(e.message)}};
 const up=$('thUpgrade');if(up&&!up.disabled)up.onclick=async()=>{up.disabled=true;try{await post(base+'/upgrade',{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('Town Hall upgrade started.')}catch(e){up.disabled=false;showNotice(e.message)}};
}
const _openBuilding=openBuilding;
openBuilding=async function(building){if(building.definition_key==='town_hall')return openTownHall();return _openBuilding(building)};
async function openWarehouse(building){
 const base=`/api/players/${state.player.id}/cities/${state.city.id}/warehouse`, d=await get(base), bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);
 const up=typeof bi.upgrade==='object'?`Cost ${Object.entries(bi.upgrade.cost).map(([k,v])=>`${esc(k)} ${fmt(v)}`).join(' · ')} · Time ${duration(bi.upgrade.seconds)}`:'Maximum level';
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Warehouse — Level ${bi.level}</h2><p>${esc(bi.purpose)}</p><div class="function-box"><b>Combined base capacity:</b> ${fmt(d.base_capacity)}<br><b>Stockpile:</b> Lv.${d.stockpile_level}<br><b>Effective capacity:</b> ${fmt(d.effective_capacity)}<br><b>Gold protected:</b> 0</div><h3>Protected Resource Allocation</h3><p>Allocation must total exactly 100%.</p><div class="th-grid">${['food','lumber','stone','iron'].map(k=>`<label>${k}<input class="wh-input" data-kind="${k}" type="number" min="0" max="100" value="${d.allocation[k]}">%</label>`).join('')}</div><button id="saveWarehouse" class="action-btn">Set Allocation</button><h3>Currently Protected</h3><p>${Object.entries(d.protected_without_privateering).map(([k,v])=>`${esc(k)} ${fmt(v)}`).join(' · ')}</p><p>Enemy Privateering reduces effective Warehouse protection by 3 percentage points per level during plunder.</p><h3>Upgrade</h3><p>${up}</p><button id="whUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;
 $('buildingModal').classList.remove('hidden');
 $('saveWarehouse').onclick=async()=>{const body={idempotency_key:crypto.randomUUID()};document.querySelectorAll('.wh-input').forEach(x=>body[x.dataset.kind]=Number(x.value));try{await post(base+'/allocation',body);showNotice('Warehouse allocation updated.');await openWarehouse(building)}catch(e){showNotice(e.message)}};
 const u=$('whUpgrade');if(u&&!u.disabled)u.onclick=async()=>{u.disabled=true;try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('Warehouse upgrade started.')}catch(e){u.disabled=false;showNotice(e.message)}};
}
const __openBuildingWarehouse=openBuilding;
openBuilding=async function(building){if(building.definition_key==='warehouse')return openWarehouse(building);return __openBuildingWarehouse(building)};

async function openAcademy(building){
 const base=`/api/players/${state.player.id}/cities/${state.city.id}/academy`,d=await get(base),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);
 const rows=d.technologies.map(t=>{const n=t.next, unknown=n&&n.seconds==='HISTORICAL_VALUE_UNKNOWN';const cost=n?Object.entries(n.cost).map(([k,v])=>`${esc(k)} ${fmt(v)}`).join(' · '):'';
 return `<div class="function-box"><b>${esc(t.name)}</b> Lv.${t.level}/10 <span>Current city: Lv.${t.effective_level_in_city}</span>${n?`<br>Next: Academy ${n.academy_level} · ${cost} · Gold ${fmt(n.gold)} · ${unknown?'Historical timer unresolved':duration(n.seconds)}<br>Tech prereqs: ${esc(JSON.stringify(n.technology_requirements))} · Building prereqs: ${esc(JSON.stringify(n.building_requirements))}<br>Effect: ${esc(n.effect.type)}`:'<br>Maximum level'}<br>${n?`<button class="action-btn research-btn" data-tech="${t.key}" ${unknown?'disabled':''}>Research Lv.${t.level+1}</button>`:''}</div>`}).join('');
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Academy — Level ${d.level}</h2><p>Research is conducted here. One active research per Academy/city.</p>${d.active_research?`<div class="queue-card">Researching ${esc(d.active_research.technology)} Lv.${d.active_research.target_level} until ${esc(String(d.active_research.completes_at))}</div>`:''}<h3>Technologies</h3>${rows}<h3>Upgrade Academy</h3><button id="academyUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;
 $('buildingModal').classList.remove('hidden');
 document.querySelectorAll('.research-btn').forEach(x=>x.onclick=async()=>{x.disabled=true;try{await post(`${base}/research/${x.dataset.tech}`,{idempotency_key:crypto.randomUUID()});await openAcademy(building);showNotice('Research started.')}catch(e){x.disabled=false;showNotice(e.message)}});
 const u=$('academyUpgrade');if(u&&!u.disabled)u.onclick=async()=>{u.disabled=true;try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('Academy upgrade started.')}catch(e){u.disabled=false;showNotice(e.message)}};
}
const ___openBuildingAcademy=openBuilding;
openBuilding=async function(building){if(building.definition_key==='academy')return openAcademy(building);return ___openBuildingAcademy(building)};

async function openRallySpot(building){
 const base=`/api/players/${state.player.id}/cities/${state.city.id}/rally-spot`,d=await get(base),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);
 const troopInputs=Object.keys(d.troops).map(k=>`<label>${esc(k)} (${fmt(d.troops[k])}) <input class="march-troop" data-kind="${k}" type="number" min="0" value="0"></label>`).join('');
 const heroOptions=`<option value="">None</option>`+d.heroes.map(h=>`<option value="${h.id}">${esc(h.name)} Lv.${h.level} — ${esc(h.status)}</option>`).join('');
 const marches=d.marches.map(m=>`<div class="queue-card"><b>${esc(m.mission)}</b> → ${m.target[0]},${m.target[1]} · ${esc(m.status)} · troops ${esc(JSON.stringify(m.army))}${['MARCHING','CAMPED','GARRISONED','ARRIVED_PENDING_RESOLUTION'].includes(m.status)?` <button class="action-btn recall-march" data-id="${m.id}">Recall</button>`:''}</div>`).join('');
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Rally Spot — Level ${d.level}</h2><p>${d.march_slots} simultaneous waves · ${fmt(d.troop_limit)} troops/wave</p><label><input id="openGates" type="checkbox" ${d.open_gates?'checked':''}> Open Gate to Fight</label><h3>Troop Overview</h3><p>${Object.entries(d.troops).map(([k,v])=>`${esc(k)} ${fmt(v)}`).join(' · ')||'No troops'}</p><h3>March</h3><div class="th-grid"><label>Mission<select id="marchMission">${d.missions.map(x=>`<option>${x}</option>`).join('')}</select></label><label>X<input id="marchX" type="number"></label><label>Y<input id="marchY" type="number"></label><label>Hero<select id="marchHero">${heroOptions}</select></label><label>Camp seconds<input id="marchCamp" type="number" min="0" max="86340" value="0"></label></div><div class="th-grid">${troopInputs}</div><h4>Resources</h4><div class="th-grid">${['food','lumber','stone','iron'].map(k=>`<label>${k}<input class="march-resource" data-kind="${k}" type="number" min="0" value="0"></label>`).join('')}</div><button id="previewMarch" class="action-btn">Preview</button> <button id="sendMarch" class="action-btn">March</button><div id="marchPreview"></div><h3>Army Movements</h3>${marches||'<p>None.</p>'}<h3>Exercise</h3><p>Historical Exercise used your own research for both sides. Exact battle-round resolution remains blocked until the combat phase rather than showing a fake prediction.</p><h3>Medic Camp</h3><p>Wounded: ${esc(JSON.stringify(d.medic_camp.wounded))}. Exact Age I healing-gold costs remain HISTORICAL_VALUE_UNKNOWN, so healing is not exposed as a fake action.</p><h3>Upgrade</h3><button id="rallyUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;
 $('buildingModal').classList.remove('hidden');
 const payload=()=>{const troops={},resources={};document.querySelectorAll('.march-troop').forEach(x=>{if(+x.value)troops[x.dataset.kind]=+x.value});document.querySelectorAll('.march-resource').forEach(x=>{if(+x.value)resources[x.dataset.kind]=+x.value});return {mission:$('marchMission').value,target_x:+$('marchX').value,target_y:+$('marchY').value,troops,resources,camp_seconds:+$('marchCamp').value,war_ensign:false}};
 $('previewMarch').onclick=async()=>{try{const p=await post(base+'/preview',payload());$('marchPreview').innerHTML=`Distance ${p.distance.toFixed(2)} · Travel ${duration(p.travel_seconds)} · Arrival ${duration(p.arrival_seconds)} · Food ${fmt(p.food_required)} · Load ${fmt(p.load_used)}/${fmt(p.load_capacity)}`}catch(e){showNotice(e.message)}};
 $('sendMarch').onclick=async()=>{const p=payload();p.hero_id=$('marchHero').value?+$('marchHero').value:null;p.idempotency_key=crypto.randomUUID();try{await post(base+'/marches',p);await openRallySpot(building);showNotice('March dispatched.')}catch(e){showNotice(e.message)}};
 $('openGates').onchange=async()=>{try{await post(base+'/open-gates',{open_gates:$('openGates').checked,idempotency_key:crypto.randomUUID()})}catch(e){showNotice(e.message)}};
 document.querySelectorAll('.recall-march').forEach(x=>x.onclick=async()=>{try{await post(`${base}/marches/${x.dataset.id}/recall`,{idempotency_key:crypto.randomUUID()});await openRallySpot(building)}catch(e){showNotice(e.message)}});
 const u=$('rallyUpgrade');if(u&&!u.disabled)u.onclick=async()=>{u.disabled=true;try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){u.disabled=false;showNotice(e.message)}};
}
const ____openBuildingRally=openBuilding;
openBuilding=async function(building){if(building.definition_key==='rally_spot')return openRallySpot(building);return ____openBuildingRally(building)};
async function openBarracks(building){
 const base=`/api/players/${state.player.id}/cities/${state.city.id}/barracks/${building.id}`,d=await get(base),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);
 const queue=d.queue.map(q=>`<div class="queue-card"><b>${esc(q.troop_type)}</b> × ${fmt(q.quantity)} — ${esc(q.status)} · ${duration(q.duration_seconds)}${q.completes_at?` · completes ${esc(String(q.completes_at))}`:''}</div>`).join('');
 const units=d.troops.map(t=>{const miss=t.missing_prerequisites.map(x=>`${x.key} Lv.${x.required} (have ${x.current})`).join(', ');const c=t.cost;return `<div class="function-box"><b>${esc(t.name)}</b> ${t.available?'':'🔒'}<br>Requires Barracks ${t.barracks_level}${Object.entries(t.technology_requirements).length?' · '+Object.entries(t.technology_requirements).map(([k,v])=>`${k} ${v}`).join(' · '):''}<br>Cost/unit: Food ${fmt(c.food)} · Lumber ${fmt(c.lumber)} · Stone ${fmt(c.stone)} · Iron ${fmt(c.iron)} · Population ${t.population}<br>Base time ${duration(t.base_training_seconds)} · Life ${t.life} · Attack ${t.attack} · Defense ${t.defense} · Load ${t.load} · Upkeep ${t.food_upkeep_per_hour}/h · Speed ${t.speed_miles_per_1000_minutes} · Range ${t.range}${miss?`<br><b>Missing:</b> ${esc(miss)}`:''}<br><input class="train-count" data-key="${t.key}" type="number" min="1" value="1" ${t.available?'':'disabled'}> <button class="action-btn train-unit" data-key="${t.key}" ${t.available?'':'disabled'}>Train</button></div>`}).join('');
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Barracks — Level ${d.level}</h2><p>This Barracks has its own queue: ${d.queue_used}/${d.queue_capacity} batches.</p><h3>Training Queue</h3>${queue||'<p>Idle.</p>'}<h3>City Troops</h3><p>${Object.entries(d.inventory).map(([k,v])=>`${esc(k)} ${fmt(v)}`).join(' · ')||'No troops'}</p><h3>Recruit</h3>${units}<h3>Upgrade Barracks</h3><button id="barracksUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;
 $('buildingModal').classList.remove('hidden');
 document.querySelectorAll('.train-unit').forEach(btn=>btn.onclick=async()=>{const input=document.querySelector(`.train-count[data-key="${btn.dataset.key}"]`);btn.disabled=true;try{await post(`${base}/train/${btn.dataset.key}`,{quantity:+input.value,idempotency_key:crypto.randomUUID()});await openBarracks(building);showNotice('Training queued.')}catch(e){btn.disabled=false;showNotice(e.message)}});
 const u=$('barracksUpgrade');if(u&&!u.disabled)u.onclick=async()=>{u.disabled=true;try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){u.disabled=false;showNotice(e.message)}};
}
const _____openBuildingBarracks=openBuilding;
openBuilding=async function(building){if(building.definition_key==='barracks')return openBarracks(building);return _____openBuildingBarracks(building)};

async function openBeaconTower(building){
 const d=await get(`/api/players/${state.player.id}/cities/${state.city.id}/beacon-tower`),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);
 const alerts=d.incoming.map(a=>`<div class="queue-card"><b>Incoming invasion</b><pre>${esc(JSON.stringify(a,null,2))}</pre></div>`).join('');
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Beacon Tower — Level ${d.level}</h2><p>Current intelligence unlock: <b>${esc(d.level_effect||'None')}</b></p><h3>Incoming Warnings</h3>${alerts||'<p>No incoming enemy movements detected.</p>'}<h3>Upgrade</h3><button id="beaconUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;
 $('buildingModal').classList.remove('hidden');const u=$('beaconUpgrade');if(u&&!u.disabled)u.onclick=async()=>{u.disabled=true;try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){u.disabled=false;showNotice(e.message)}};
}
const _____openBuildingBeacon=openBuilding;
openBuilding=async function(building){if(building.definition_key==='beacon_tower')return openBeaconTower(building);return _____openBuildingBeacon(building)};

async function openForge(building){const d=await get(`/api/players/${state.player.id}/cities/${state.city.id}/forge`),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);$('modalBody').innerHTML=`<div class="building-panel"><h2>Forge — Level ${d.level}</h2><p>Supports Military Science through Level ${d.military_science_supported_level}.</p><p>Workshop construction: <b>${d.workshop_unlocked?'Unlocked':'Requires Forge Level 2'}</b></p><p>${d.dependencies.map(esc).join('<br>')}</p><button id="forgeUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;$('buildingModal').classList.remove('hidden');const u=$('forgeUpgrade');if(u&&!u.disabled)u.onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){showNotice(e.message)}}}
const ______openBuildingForge=openBuilding;openBuilding=async function(building){if(building.definition_key==='forge')return openForge(building);return ______openBuildingForge(building)};

async function openStable(building){const d=await get(`/api/players/${state.player.id}/cities/${state.city.id}/stable`),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);$('modalBody').innerHTML=`<div class="building-panel"><h2>Stable — Level ${d.level}</h2><p>Horseback Riding supported through Lv.${d.horseback_riding_supported_level}.</p><p>Relief Station: ${d.relief_station_unlocked?'Unlocked':'Locked'}</p><p>${esc(d.note)}</p><button id="stableUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;$('buildingModal').classList.remove('hidden');const u=$('stableUpgrade');if(u&&!u.disabled)u.onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){showNotice(e.message)}}}
const _______openBuildingStable=openBuilding;openBuilding=async function(building){if(building.definition_key==='stable')return openStable(building);return _______openBuildingStable(building)};

async function openWorkshop(building){const d=await get(`/api/players/${state.player.id}/cities/${state.city.id}/workshop`),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);$('modalBody').innerHTML=`<div class="building-panel"><h2>Workshop — Level ${d.level}</h2><p>Metal Casting supported through Lv.${d.metal_casting_supported_level}. Walls: ${d.walls_unlocked?'Unlocked':'Locked'}.</p><p>${d.dependencies.map(esc).join('<br>')}</p><button id="workshopUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;$('buildingModal').classList.remove('hidden');const u=$('workshopUpgrade');if(u&&!u.disabled)u.onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){showNotice(e.message)}}}
const ________openBuildingWorkshop=openBuilding;openBuilding=async function(building){if(building.definition_key==='workshop')return openWorkshop(building);return ________openBuildingWorkshop(building)};

async function openReliefStation(building){const d=await get(`/api/players/${state.player.id}/cities/${state.city.id}/relief-station`),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);$('modalBody').innerHTML=`<div class="building-panel"><h2>Relief Station — Level ${d.level}</h2><p>Own/allied city Transport & Reinforce speed: <b>${d.speed_multiplier}×</b></p><p>Sending city's Relief Station controls the bonus. It does not accelerate attacks, scouts, enemy-city movement, or valley/NPC attacks.</p><button id="reliefUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;$('buildingModal').classList.remove('hidden');const u=$('reliefUpgrade');if(u&&!u.disabled)u.onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){showNotice(e.message)}}}
const _________openBuildingRelief=openBuilding;openBuilding=async function(building){if(building.definition_key==='relief_station')return openReliefStation(building);return _________openBuildingRelief(building)};

async function openWalls(building){const base=`/api/players/${state.player.id}/cities/${state.city.id}/walls`,d=await get(base),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);const defs=d.definitions.map(x=>`<div class="function-box"><b>${esc(x.name)}</b> · space ${x.space} · ${duration(x.base_seconds)} each<br>Cost: ${Object.entries(x.cost).filter(([,v])=>v).map(([k,v])=>`${k} ${fmt(v)}`).join(' · ')}<br>Range: ${fmt(x.effective_range??x.range??x.base_range??0)}${x.attack?` · Attack ${fmt(x.attack)}`:''}${x.life?` · Life ${esc(String(x.life))}`:''}${x.defense?` · Defense ${fmt(x.defense)}`:''}${x.attack_effect?` · Effect: ${esc(x.attack_effect.replaceAll('_',' '))}`:''}<br>${x.missing_prerequisites.length?'Missing: '+esc(JSON.stringify(x.missing_prerequisites)):`Current ${fmt(d.fortifications[x.key]||0)} <input id="fort-${x.key}" type="number" min="1" value="1"> <button class="action-btn fort-build" data-key="${x.key}">Build</button>`}</div>`).join('');$('modalBody').innerHTML=`<div class="building-panel"><h2>Walls — Level ${d.level}</h2><p>Durability ${fmt(d.durability)} · Effective ${fmt(d.effective_durability)} · Fortified space ${fmt(d.used)}/${fmt(d.spaces)} · ${d.queue_slots} queue slots</p><p>Archer Tower effective range: ${fmt(d.defensive_interaction.archer_tower_range)}</p><h3>Fortifications</h3>${defs}<h3>Queue</h3>${d.queue.map(q=>`<div class="queue-card">${esc(q.type)} × ${fmt(q.quantity)} — ${esc(q.status)}</div>`).join('')||'<p>Empty</p>'}<h3>Upgrade Walls</h3><button id="wallsUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;$('buildingModal').classList.remove('hidden');document.querySelectorAll('.fort-build').forEach(x=>x.onclick=async()=>{try{await post(base+'/fortifications',{definition_key:x.dataset.key,quantity:+$(`fort-${x.dataset.key}`).value,idempotency_key:crypto.randomUUID()});await openWalls(building)}catch(e){showNotice(e.message)}});const u=$('wallsUpgrade');if(u&&!u.disabled)u.onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){showNotice(e.message)}}}
const __________openBuildingWalls=openBuilding;openBuilding=async function(building){if(building.definition_key==='walls')return openWalls(building);return __________openBuildingWalls(building)};

const ___________openBuildingDemolition=openBuilding;
openBuilding=async function(building){await ___________openBuildingDemolition(building);if(building.definition_key==='town_hall')return;const panel=$('modalBody').querySelector('.building-panel');if(!panel)return;const box=document.createElement('div');box.className='function-box';box.innerHTML=`<h3>Demolish Building</h3><p>Demolish by one level uses labor, takes time, and returns 30% of that level's construction resources. Dynamite removes a normal building immediately, returns no resources, and consumes 1 Dynamite.</p><button id="demoOne" class="action-btn">Demolish by One Level</button> ${building.definition_key==='walls'?'':`<button id="demoDynamite" class="action-btn">Completely Demolish — 1 Dynamite</button>`}`;panel.appendChild(box);$('demoOne').onclick=async()=>{try{const r=await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/demolish-one-level`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice(`Demolition started: Lv.${r.from_level} → Lv.${r.to_level}`)}catch(e){showNotice(e.message)}};const d=$('demoDynamite');if(d)d.onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/dynamite`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('Building demolished.')}catch(e){showNotice(e.message)}}};
async function openEmptyField(plot){
 const d=await get(`/api/players/${state.player.id}/cities/${state.city.id}/field-construction-options`);
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Resource Field — Plot ${plot.plot_index}</h2><p>Choose the resource building for this plot. There is no balancing restriction.</p><div class="build-list">${d.options.map(o=>`<div class="build-option"><h3>${esc(o.name)}</h3><p>${esc(o.purpose)}</p><div class="costs">${Object.entries(o.cost).map(([k,v])=>`<span>${esc(k)} ${fmt(v)}</span>`).join('')}<span>Time ${duration(o.seconds)}</span></div><p>Labor ${fmt(o.labor)} · Output ${fmt(o.production_per_hour)}/hr · Capacity ${fmt(o.storage_capacity)}</p><button class="action-btn field-construct" data-key="${o.key}">Construct</button></div>`).join('')}</div></div>`;
 $('buildingModal').classList.remove('hidden');document.querySelectorAll('.field-construct').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/fields/${plot.plot_index}/construct`,{building_key:b.dataset.key,idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('Resource-field construction started.')}catch(e){b.disabled=false;showNotice(e.message)}})
}
async function openResourceField(building){
 const view=await get(`/api/players/${state.player.id}/cities/${state.city.id}/field-view`),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`),kind={farm:'food',sawmill:'lumber',quarry:'stone',ironmine:'iron'}[building.definition_key],r=view.production.resources[kind],up=bi.upgrade;
 $('modalBody').innerHTML=`<div class="building-panel"><h2>${esc(bi.name)} — Level ${bi.level}</h2><div class="function-box"><b>Base output:</b> ${fmt(r.base_per_hour)}/hr<br><b>Effective output:</b> ${fmt(Math.round(r.effective_per_hour))}/hr<br><b>Labor:</b> ${fmt(r.labor)} base · ${fmt(Math.round(r.assigned_labor))} assigned<br><b>Storage capacity:</b> ${fmt(r.capacity)} total city ${esc(kind)} capacity<br><b>Production setting:</b> ${r.production_percent}%<br><b>Technology:</b> +${r.technology_bonus_percent}% · <b>Mayor Politics:</b> +${r.mayor_bonus_percent}% · <b>Valleys:</b> +${r.valley_bonus_percent}% · <b>Items:</b> +${r.item_bonus_percent}%</div><h3>Upgrade</h3><p>${typeof up==='object'?`${Object.entries(up.cost).map(([k,v])=>`${esc(k)} ${fmt(v)}`).join(' · ')} · ${duration(up.seconds)}${Object.keys(up.item_cost||{}).length?' · '+Object.entries(up.item_cost).map(([k,v])=>`${esc(k)} ×${v}`).join(' '):''}`:'Maximum Level'}</p><button id="resourceUpgrade" class="action-btn" ${typeof up==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button><h3>Demolish / Downgrade</h3><button id="resourceDemoOne" class="action-btn">Demolish by One Level</button> <button id="resourceDynamite" class="action-btn">Completely Demolish — 1 Dynamite</button></div>`;
 $('buildingModal').classList.remove('hidden');const u=$('resourceUpgrade');if(u&&!u.disabled)u.onclick=async()=>{u.disabled=true;try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('Resource-field upgrade started.')}catch(e){u.disabled=false;showNotice(e.message)}};$('resourceDemoOne').onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/demolish-one-level`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('Resource-field downgrade started.')}catch(e){showNotice(e.message)}};$('resourceDynamite').onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/dynamite`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id);showNotice('Resource field demolished.')}catch(e){showNotice(e.message)}}
}
async function handleFieldPlot(plot){if(plot.locked)return showNotice('This resource plot is locked. Upgrade the Town Hall to unlock three more plots.');if(plot.building)return openResourceField(plot.building);return openEmptyField(plot)}

async function openEconomyDebug(){
 try{
  const d=await get(`/api/dev/players/${state.player.id}/cities/${state.city.id}/economy-debug`);
  const resources=Object.entries(d.resources).map(([k,v])=>`<div class="function-box"><b>${esc(k)}</b><br>Base ${fmt(v.base_per_hour)}/h · production ${v.production_percent}% · labor ${fmt(v.assigned_labor)} · population factor ${Number(v.population_factor).toFixed(4)}<br>Tech +${v.technology_bonus_percent}% · Mayor +${v.mayor_bonus_percent}% · Valley +${v.valley_bonus_percent}% · Items +${v.item_bonus_percent}%<br><b>Gross ${fmt(v.effective_per_hour)}/h</b></div>`).join('');
  $('modalBody').innerHTML=`<div class="building-panel"><h2>Economy Debug — Development Only</h2><h3>Population</h3><pre>${esc(JSON.stringify(d.population,null,2))}</pre><h3>Resources</h3>${resources}<h3>Food</h3><p>Gross ${fmt(d.gross_food_per_hour)}/h · garrison upkeep ${fmt(d.troop_food.garrisoned_per_hour)}/h · outside upkeep ${fmt(d.troop_food.outside_per_hour)}/h · <b>net ${fmt(d.net_food_per_hour)}/h</b></p><h3>Gold</h3><p>Tax gross ${fmt(d.gross_gold_per_hour)}/h · hero salary ${fmt(d.hero_salary_per_hour)}/h · <b>net ${fmt(d.net_gold_per_hour)}/h</b></p><h3>Storage / Protection</h3><p>Warehouse ${fmt(d.warehouse_capacity)} · protected ${esc(JSON.stringify(d.warehouse_protected))}</p><h3>Formulae</h3><pre>${esc(JSON.stringify(d.formulae,null,2))}</pre><h3>Historical Unknowns</h3><pre>${esc(JSON.stringify(d.historical_unknowns,null,2))}</pre></div>`;
  $('buildingModal').classList.remove('hidden');
 }catch(e){showNotice(e.message)}
}

async function openFeastingHall(building){
 const base=`/api/players/${state.player.id}/cities/${state.city.id}/feasting-hall`,d=await get(base),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);
 const cards=d.heroes.map(h=>`<div class="function-box"><b>${esc(h.name)}</b> Lv.${h.level} — ${esc(h.status.key)}<br>P ${h.politics} · A ${h.attack} · I ${h.intelligence} · Loyalty ${h.loyalty} · XP ${fmt(h.experience)} · Salary ${fmt(h.salary_per_hour)}/h<br><button class="action-btn hero-view" data-id="${h.id}">View</button> ${h.status.key==='idle'?`<button class="action-btn hero-mayor" data-id="${h.id}">Appoint Mayor</button>`:''} ${h.captured?`<button class="action-btn hero-persuade" data-id="${h.id}">Persuade</button> <button class="action-btn hero-release" data-id="${h.id}">Release</button>`:`<button class="action-btn hero-dismiss" data-id="${h.id}">Dismiss</button>`}</div>`).join('');
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Feasting Hall — Level ${d.level}</h2><p>Heroes ${d.occupied}/${d.capacity}. Mayor P/A/I: ${d.mayor_effects.stats.politics}/${d.mayor_effects.stats.attack}/${d.mayor_effects.stats.intelligence}</p>${cards||'<p>No heroes.</p>'}<button id="fhUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;$('buildingModal').classList.remove('hidden');
 document.querySelectorAll('.hero-view').forEach(x=>x.onclick=()=>openHeroDetail(building,+x.dataset.id));
 document.querySelectorAll('.hero-mayor').forEach(x=>x.onclick=async()=>{try{await post(`${base}/heroes/${x.dataset.id}/appoint-mayor`,{idempotency_key:crypto.randomUUID()});await openFeastingHall(building)}catch(e){showNotice(e.message)}});
 document.querySelectorAll('.hero-dismiss').forEach(x=>x.onclick=async()=>{try{await post(`${base}/heroes/${x.dataset.id}/dismiss`,{idempotency_key:crypto.randomUUID()});await openFeastingHall(building)}catch(e){showNotice(e.message)}});
 document.querySelectorAll('.hero-persuade').forEach(x=>x.onclick=async()=>{try{await post(`${base}/heroes/${x.dataset.id}/persuade`,{idempotency_key:crypto.randomUUID()});await openFeastingHall(building)}catch(e){showNotice(e.message)}});
 document.querySelectorAll('.hero-release').forEach(x=>x.onclick=async()=>{try{await post(`${base}/heroes/${x.dataset.id}/release`,{idempotency_key:crypto.randomUUID()});await openFeastingHall(building)}catch(e){showNotice(e.message)}});
}
async function openHeroDetail(building,id){
 const base=`/api/players/${state.player.id}/cities/${state.city.id}/feasting-hall/heroes/${id}`,h=await get(base);
 $('modalBody').innerHTML=`<div class="building-panel"><h2>${esc(h.name)} — Level ${h.level}</h2><p>Status ${esc(h.status.key)} · Loyalty ${h.loyalty} · Salary ${fmt(h.salary_per_hour)}/h</p><p>Politics ${h.politics} (${h.effective_stats.politics}) · Attack ${h.attack} (${h.effective_stats.attack}) · Intelligence ${h.intelligence} (${h.effective_stats.intelligence})</p><p>Experience ${fmt(h.experience)} / ${fmt(h.experience_needed)} · Unassigned points ${h.unassigned_attribute_points}</p><h3>Upgrade</h3><button class="action-btn hero-level" data-a="politics">+ Politics</button> <button class="action-btn hero-level" data-a="attack">+ Attack</button> <button class="action-btn hero-level" data-a="intelligence">+ Intelligence</button><h3>Rewards</h3><button id="heroGold" class="action-btn">Gold Reward (+5 Loyalty)</button> <select id="heroItem"><option value="anabasis">Anabasis</option><option value="epitome_of_military_science">Epitome of Military Science</option><option value="on_war">On War</option><option value="wealth_of_nations">Wealth of Nations</option><option value="excalibur">Excalibur</option><option value="the_art_of_war">The Art of War</option></select> <button id="heroUseItem" class="action-btn">Apply Item</button><h3>Redistribute</h3><button id="heroRedistribute" class="action-btn">Use Holy Water</button><h3>Rename</h3><input id="heroName" value="${esc(h.name)}"><button id="heroRename" class="action-btn">Rename</button><br><button id="heroBack" class="action-btn">Back</button></div>`;
 document.querySelectorAll('.hero-level').forEach(x=>x.onclick=async()=>{try{await post(base+'/level',{attribute:x.dataset.a,idempotency_key:crypto.randomUUID()});await openHeroDetail(building,id)}catch(e){showNotice(e.message)}});
 $('heroGold').onclick=async()=>{try{await post(base+'/reward-gold',{idempotency_key:crypto.randomUUID()});await openHeroDetail(building,id)}catch(e){showNotice(e.message)}};
 $('heroUseItem').onclick=async()=>{try{await post(base+'/item',{item_key:$('heroItem').value,idempotency_key:crypto.randomUUID()});await openHeroDetail(building,id)}catch(e){showNotice(e.message)}};
 $('heroRedistribute').onclick=async()=>{try{await post(base+'/redistribute',{idempotency_key:crypto.randomUUID()});await openHeroDetail(building,id)}catch(e){showNotice(e.message)}};
 $('heroRename').onclick=async()=>{try{await post(base+'/rename',{name:$('heroName').value,idempotency_key:crypto.randomUUID()});await openHeroDetail(building,id)}catch(e){showNotice(e.message)}};
 $('heroBack').onclick=()=>openFeastingHall(building);
}
const ____________openBuildingHeroes=openBuilding;openBuilding=async function(building){if(building.definition_key==='feasting_hall')return openFeastingHall(building);return ____________openBuildingHeroes(building)};

async function openReports(){
 const d=await get(`/api/players/${state.player.id}/reports`);
 const rows=d.reports.map(r=>`<div class="function-box"><b>${r.read?'':'● '}${esc(r.kind.toUpperCase())}</b> · ${new Date(r.created_at).toLocaleString()}<br><button class="action-btn report-open" data-k="${r.kind}" data-id="${r.id}">Open</button> <button class="action-btn report-delete" data-k="${r.kind}" data-id="${r.id}">Delete</button></div>`).join('');
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Reports</h2>${rows||'<p>No reports.</p>'}</div>`;$('buildingModal').classList.remove('hidden');
 document.querySelectorAll('.report-open').forEach(b=>b.onclick=async()=>{const r=await get(`/api/players/${state.player.id}/reports/${b.dataset.k}/${b.dataset.id}`);$('modalBody').innerHTML=`<div class="building-panel"><h2>${esc(r.kind.toUpperCase())} Report</h2><pre>${esc(JSON.stringify(r.payload,null,2))}</pre><button id="reportsBack" class="action-btn">Back</button></div>`;$('reportsBack').onclick=openReports});
 document.querySelectorAll('.report-delete').forEach(b=>b.onclick=async()=>{await request(`/api/players/${state.player.id}/reports/${b.dataset.k}/${b.dataset.id}`,{method:'DELETE'});await openReports()});
}
if($('reportsButton'))$('reportsButton').onclick=openReports;

async function openMail(box='inbox'){
 const d=await request(`/api/players/${state.playerId}/mail?box=${box}`);
 const rows=(d.messages||[]).map(m=>`<button class="function-box mail-open" data-id="${m.id}"><b>${esc(box==='sent'?`To: ${m.recipient}`:`${m.read?'':'● '}${m.sender}`)}</b><br>${esc(m.subject)}<br><small>${new Date(m.timestamp).toLocaleString()}</small></button>`).join('')||'<p>No messages.</p>';
 showModal(`<h2>Mail</h2><div class="building-tabs"><button class="action-btn mail-box" data-box="inbox">Inbox</button><button class="action-btn mail-box" data-box="sent">Sent</button><button class="action-btn" id="mailCompose">Compose</button></div>${rows}`);
 document.querySelectorAll('.mail-box').forEach(b=>b.onclick=()=>openMail(b.dataset.box));
 document.querySelectorAll('.mail-open').forEach(b=>b.onclick=()=>openMailMessage(Number(b.dataset.id),box));
 $('mailCompose').onclick=()=>composeMail();
}
async function openMailMessage(id,box='inbox'){
 const m=await request(`/api/players/${state.playerId}/mail/${id}`);
 showModal(`<h2>${esc(m.subject)}</h2><p><b>From:</b> ${esc(m.sender)}<br><b>To:</b> ${esc(m.recipient)}<br><b>Time:</b> ${new Date(m.timestamp).toLocaleString()}</p><div class="function-box mail-body">${esc(m.body).replaceAll('\n','<br>')}</div><div class="modal-actions">${m.sender_player_id&&m.recipient_player_id===state.playerId?'<button class="action-btn" id="mailReply">Reply</button>':''}<button class="action-btn danger" id="mailDelete">Delete</button><button class="action-btn" id="mailBack">Back</button></div>`);
 if($('mailReply'))$('mailReply').onclick=()=>composeMail(m.sender,m.subject.startsWith('Re:')?m.subject:`Re: ${m.subject}`,id);
 $('mailDelete').onclick=async()=>{await request(`/api/players/${state.playerId}/mail/${id}?box=${box}`,{method:'DELETE'});openMail(box)};
 $('mailBack').onclick=()=>openMail(box);
}
function composeMail(recipient='',subject='',replyId=null){
 showModal(`<h2>${replyId?'Reply':'Compose Mail'}</h2><label>Recipient<input id="mailRecipient" maxlength="64" value="${esc(recipient)}" ${replyId?'readonly':''}></label><div id="mailRecipientMatches"></div><label>Subject<input id="mailSubject" maxlength="120" value="${esc(subject)}"></label><label>Message<textarea id="mailBody" maxlength="5000" rows="10"></textarea></label><button class="action-btn" id="mailSend">Send</button>`);
 let timer=null;$('mailRecipient').oninput=()=>{clearTimeout(timer);timer=setTimeout(async()=>{const q=$('mailRecipient').value.trim();if(q.length<2)return $('mailRecipientMatches').innerHTML='';const d=await request(`/api/players/${state.playerId}/mail/recipients?q=${encodeURIComponent(q)}`);$('mailRecipientMatches').innerHTML=d.recipients.map(x=>`<button class="action-btn recipient-pick" data-name="${esc(x.name)}">${esc(x.name)}</button>`).join('');document.querySelectorAll('.recipient-pick').forEach(b=>b.onclick=()=>{$('mailRecipient').value=b.dataset.name;$('mailRecipientMatches').innerHTML=''})},250)};
 $('mailSend').onclick=async()=>{await request(`/api/players/${state.playerId}/mail`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipient:$('mailRecipient').value,subject:$('mailSubject').value,body:$('mailBody').value,idempotency_key:crypto.randomUUID(),reply_to_mail_id:replyId})});showNotice('Mail sent.');openMail('sent')};
}
document.addEventListener('DOMContentLoaded',()=>{const b=$('mailButton');if(b)b.onclick=()=>openMail()});

async function openAlliance(){
 const d=await request(`/api/players/${state.playerId}/alliance`);
 if(!d.alliance){showModal(`<h2>Alliance</h2><p>You are not currently in an alliance. Joining and creating alliances is handled through the Embassy.</p>`);return}
 const a=d.alliance;const members=a.members.map(m=>`<div class="function-box"><b>${esc(m.name)}</b> · ${esc(m.rank.replaceAll('_',' '))}</div>`).join('');
 showModal(`<h2>${esc(a.name)}</h2><p>${esc(a.information||'No alliance information.')}</p><p>Your rank: <b>${esc(a.my_rank.replaceAll('_',' '))}</b></p><h3>Members</h3>${members}<h3>Alliance Chat</h3><div id="allianceChat"></div><textarea id="allianceChatBody" maxlength="500" rows="3"></textarea><button class="action-btn" id="allianceChatSend">Send</button>`);
 const load=async()=>{const c=await request(`/api/players/${state.playerId}/alliance/chat`);$('allianceChat').innerHTML=c.messages.map(x=>`<div><b>${esc(x.player)}:</b> ${esc(x.body)} <small>${new Date(x.timestamp).toLocaleTimeString()}</small></div>`).join('')};
 await load();$('allianceChatSend').onclick=async()=>{await request(`/api/players/${state.playerId}/alliance/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:$('allianceChatBody').value})});$('allianceChatBody').value='';await load()};
}
document.addEventListener('DOMContentLoaded',()=>{const b=$('allianceButton');if(b)b.onclick=()=>openAlliance()});

let chatPoll=null,chatChannel='WORLD',chatLast=0;
async function openChat(channel='WORLD'){
 chatChannel=channel;chatLast=0;if(chatPoll)clearInterval(chatPoll);
 showModal(`<h2>Chat</h2><div class="building-tabs"><button class="action-btn chat-tab" data-c="WORLD">World</button><button class="action-btn chat-tab" data-c="ALLIANCE">Alliance</button><button class="action-btn chat-tab" data-c="WHISPER">Whisper</button></div><div id="chatMessages" class="chat-messages"></div><div id="whisperRecipient" class="${channel==='WHISPER'?'':'hidden'}"><label>Whisper to <input id="chatRecipient" maxlength="64"></label></div><textarea id="chatBody" maxlength="500" rows="3"></textarea><button class="action-btn" id="chatSend">Send</button>`);
 document.querySelectorAll('.chat-tab').forEach(b=>b.onclick=()=>openChat(b.dataset.c));
 const poll=async()=>{try{const d=await request(`/api/players/${state.playerId}/chat?channel=${chatChannel}&since_id=${chatLast}`);for(const m of d.messages){chatLast=Math.max(chatLast,m.id);const div=document.createElement('div');div.className='chat-line';div.innerHTML=`<b>${esc(m.sender)}</b>${m.recipient?` → ${esc(m.recipient)}`:''}: ${esc(m.body)} <small>${new Date(m.timestamp).toLocaleTimeString()}</small>`;$('chatMessages')?.appendChild(div)}if($('chatMessages'))$('chatMessages').scrollTop=$('chatMessages').scrollHeight}catch(e){}};
 await poll();chatPoll=setInterval(poll,1500);
 $('chatSend').onclick=async()=>{await request(`/api/players/${state.playerId}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel:chatChannel,body:$('chatBody').value,recipient:chatChannel==='WHISPER'?$('chatRecipient').value:null})});$('chatBody').value='';await poll()};
}
document.addEventListener('DOMContentLoaded',()=>{const b=$('chatButton');if(b)b.onclick=()=>openChat()});

async function openQuests(){
 const d=await request(`/api/players/${state.playerId}/quests`);
 const rows=d.quests.map(q=>`<div class="function-box"><b>${esc(q.name)}</b> · ${esc(q.category)}<br>${q.requirements.map(r=>`${r.met?'✓':'○'} ${esc(r.requirement.type.replaceAll('_',' '))}: ${esc(String(r.value))}`).join('<br>')}<br>${q.claimed?'Award claimed':q.completed?`<button class="action-btn quest-claim" data-key="${esc(q.key)}">Get Award</button>`:'In progress'}${q.reward_status==='HISTORICAL_VALUE_UNKNOWN'?'<br><small>Exact historical reward unresolved.</small>':''}</div>`).join('');
 showModal(`<h2>Quests</h2>${rows}`);
 document.querySelectorAll('.quest-claim').forEach(b=>b.onclick=async()=>{await request(`/api/players/${state.playerId}/quests/${b.dataset.key}/claim`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idempotency_key:crypto.randomUUID()})});await loadStatus();openQuests()});
}
document.addEventListener('DOMContentLoaded',()=>{const b=$('questButton');if(b)b.onclick=()=>openQuests()});

async function openProgression(){
 const d=await request(`/api/players/${state.playerId}/progression?city_id=${state.cityId}`);
 const panel=(p,label)=>!p?`<p>Highest ${label} reached.</p>`:`<div class="function-box"><h3>${label}: ${esc(p.current)} → ${esc(p.next)}</h3>${p.requirements.map(r=>`<div>${r.satisfied?'✓':'✗'} ${esc(r.type.replaceAll('_',' '))}: ${esc(String(r.current))} / ${esc(String(r.required))}${r.consumed_on_promotion?' (spent)':''}</div>`).join('')}<button class="action-btn progression-promote" data-kind="${p.kind}" data-target="${esc(p.next)}" ${p.satisfied?'':'disabled'}>Promote</button></div>`;
 showModal(`<h2>Rank & Title</h2><p>Prestige: <b>${d.prestige}</b> · Honor: <b>${d.honor}</b></p><p>Rank: <b>${esc(d.rank)}</b> · Title: <b>${esc(d.title)}</b> · Cities: ${d.cities_owned}/${d.city_limit}</p>${panel(d.rank_promotion,'Rank')}${panel(d.title_promotion,'Title')}`);
 document.querySelectorAll('.progression-promote').forEach(b=>b.onclick=async()=>{await request(`/api/players/${state.playerId}/progression/promote`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({city_id:state.cityId,kind:b.dataset.kind,target:b.dataset.target,idempotency_key:crypto.randomUUID()})});await loadStatus();openProgression()});
}
document.addEventListener('DOMContentLoaded',()=>{const b=$('progressionButton');if(b)b.onclick=()=>openProgression()});

async function openItems(){
 const d=await request(`/api/players/${state.playerId}/items`);
 const buffs=d.active_buffs.map(b=>`<div class="function-box"><b>${esc(b.buff_key.replaceAll('_',' '))}</b><br>Expires ${new Date(b.expires_at).toLocaleString()}</div>`).join('');
 const rows=d.items.map(i=>`<div class="function-box"><b>${esc(i.name)}</b> × ${i.quantity}<br><small>${esc(i.category)}${i.targets.length?' · target: '+esc(i.targets.join(', ')):''}</small>${i.usable_directly?'<br><small>Use from the relevant building/hero/queue context.</small>':'<br><small>Consumed automatically by its associated game mechanic.</small>'}</div>`).join('');
 showModal(`<h2>My Items</h2>${rows||'<p>No supported items in inventory.</p>'}<h3>Active Effects</h3>${buffs||'<p>No active timed effects.</p>'}`);
}
document.addEventListener('DOMContentLoaded',()=>{const b=$('itemsButton');if(b)b.onclick=()=>openItems()});

async function refreshBeginnerProtection(){
 if(!state.playerId)return;
 try{
  const bp=await request(`/api/players/${state.playerId}/beginner-protection`);
  const el=$('beginnerProtection');if(!el)return;
  if(!bp.active){el.textContent='BP Ended';el.title=`Beginner Protection ended: ${bp.end_reason||'expired'}`;return;}
  const d=Math.floor(bp.seconds_remaining/86400),h=Math.floor((bp.seconds_remaining%86400)/3600),m=Math.floor((bp.seconds_remaining%3600)/60);
  el.textContent=`BP ${d}d ${h}h ${m}m`;el.title='Beginner Protection active. Ends after 7 days or when any Town Hall reaches level 5.';
 }catch(e){}
}
document.addEventListener('DOMContentLoaded',()=>{setTimeout(refreshBeginnerProtection,250);setInterval(refreshBeginnerProtection,60000)});

function renderClassicChrome(){
 if(!state.city||!state.player)return;
 const cities=state.cities||[];
 const rail=$('cityRail');if(rail){rail.innerHTML=cities.map(c=>`<button class="city-tab ${c.id===state.city.id?'active':''}" data-city="${c.id}"><b>${esc(c.name)}</b><small>(${c.x}, ${c.y})</small></button>`).join('');rail.querySelectorAll('.city-tab').forEach(b=>b.onclick=()=>selectCity(+b.dataset.city))}
 const c=state.city,p=state.player,box=$('rightCitySummary');if(box)box.innerHTML=[
 ['Coordinates',`(${c.coordinates.x}, ${c.coordinates.y})`],['Population',`${fmt(c.population.total)} / ${fmt(c.population.idle)} idle`],['Gold',fmt(c.economy.gold)],['Tax',`${c.economy.tax_rate}%`],['Loyalty',c.economy.loyalty],['Grievance',c.economy.grievance],['Prestige',fmt(p.prestige)],['Honor',fmt(p.honor)],['Title',p.title_rank_key||'—']
 ].map(([k,v])=>`<div class="city-summary-row"><span>${k}</span><b>${v}</b></div>`).join('');
}
const __classicRenderHUD=renderHUD;renderHUD=function(){__classicRenderHUD();renderClassicChrome()};

function updateServerClock(){const el=$('serverClock');if(el)el.textContent='Server time '+new Date().toLocaleString([], {hour12:false})}
setInterval(updateServerClock,1000);updateServerClock();

async function openInn(building){
 const base=`/api/players/${state.player.id}/cities/${state.city.id}/inn`,d=await get(base),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);
 const candidates=d.candidates.map(c=>`<div class="function-box"><b>${esc(c.name)}</b> Lv.${c.level}<br>P ${c.politics} · A ${c.attack} · I ${c.intelligence} · Loyalty ${c.loyalty}<br>Employment fee ${fmt(c.employment_fee)} gold · refresh ${esc(String(c.refreshes_at))}<br><button class="action-btn inn-recruit" data-id="${c.id}" ${d.feasting_hall.vacancies>0?'':'disabled'}>Recruit</button></div>`).join('');
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Inn — Level ${d.level}</h2><div class="function-box">Candidates ${d.candidates.length}/${d.candidate_capacity} · Feasting Hall ${d.feasting_hall.occupied}/${d.feasting_hall.capacity}</div><h3>Hero Candidates</h3>${candidates||'<p>No candidates available.</p>'}<p class="unfinished">${esc(d.refresh.status)}</p><h3>Upgrade Inn</h3><button id="innUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;$('buildingModal').classList.remove('hidden');
 document.querySelectorAll('.inn-recruit').forEach(b=>b.onclick=async()=>{try{await post(`${base}/candidates/${b.dataset.id}/recruit`,{idempotency_key:crypto.randomUUID()});await openInn(building)}catch(e){showNotice(e.message)}});
 const u=$('innUpgrade');if(u&&!u.disabled)u.onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){showNotice(e.message)}};
}
async function openMarketplace(building){
 const base=`/api/players/${state.player.id}/cities/${state.city.id}/marketplace`,d=await get(base),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);
 const orders=d.orders.map(o=>`<div class="queue-card">#${o.id} ${esc(o.side)} ${esc(o.resource)} ${fmt(o.remaining)}/${fmt(o.quantity)} @ ${o.price} · ${esc(o.status)} ${['OPEN','PARTIAL'].includes(o.status)?`<button class="action-btn market-cancel" data-id="${o.id}">Cancel</button>`:''}</div>`).join('');
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Marketplace — Level ${d.level}</h2><div class="function-box">Orders ${d.orders.filter(o=>['OPEN','PARTIAL'].includes(o.status)).length}/${d.concurrent_capacity} · Fee ${(d.fee_rate*100).toFixed(1)}%</div><h3>Place Order</h3><div class="th-grid"><label>Side<select id="marketSide"><option>BUY</option><option>SELL</option></select></label><label>Resource<select id="marketResource">${d.resources.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Quantity<input id="marketQty" type="number" min="1" max="${d.max_quantity}" value="1000"></label><label>Price<input id="marketPrice" type="number" min=".001" step=".001" value="1"></label></div><button id="marketPlace" class="action-btn">Place Order</button><h3>Orders</h3>${orders||'<p>No open orders.</p>'}<h3>Upgrade Marketplace</h3><button id="marketUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;$('buildingModal').classList.remove('hidden');
 $('marketPlace').onclick=async()=>{try{await post(base+'/orders',{side:$('marketSide').value,resource_kind:$('marketResource').value,quantity:+$('marketQty').value,price:+$('marketPrice').value,idempotency_key:crypto.randomUUID()});await openMarketplace(building)}catch(e){showNotice(e.message)}};
 document.querySelectorAll('.market-cancel').forEach(b=>b.onclick=async()=>{try{await post(`${base}/orders/${b.dataset.id}/cancel`,{idempotency_key:crypto.randomUUID()});await openMarketplace(building)}catch(e){showNotice(e.message)}});
 const u=$('marketUpgrade');if(u&&!u.disabled)u.onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){showNotice(e.message)}};
}
async function openEmbassy(building){
 const base=`/api/players/${state.player.id}/cities/${state.city.id}/embassy`,d=await get(base),bi=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);
 const gs=d.garrisons.map(g=>`<div class="queue-card">Player ${g.owner_player_id} · ${esc(JSON.stringify(g.troops))} · ${esc(g.status)} <button class="action-btn garrison-return" data-id="${g.id}">Send Home</button></div>`).join('');
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Embassy — Level ${d.level}</h2><div class="function-box">Alliance: ${d.alliance?`#${d.alliance.alliance_id} · ${esc(d.alliance.rank)}`:'None'}<br>Foreign garrisons ${d.garrisoned_waves}/${d.garrison_capacity}</div><label><input id="embassyAllow" type="checkbox" ${d.allow_allied_garrison?'checked':''}> Allow allied troops to garrison this city</label><h3>Reinforcements</h3>${gs||'<p>No allied garrisons.</p>'}<p>Alliance membership, applications, invitations, ranks and alliance mail are available through the Alliance panel.</p><button id="embassyAlliance" class="action-btn">Open Alliance</button><h3>Upgrade Embassy</h3><button id="embassyUpgrade" class="action-btn" ${typeof bi.upgrade==='object'?'':'disabled'}>Upgrade to Level ${bi.level+1}</button></div>`;$('buildingModal').classList.remove('hidden');
 $('embassyAllow').onchange=async()=>{try{await post(base+'/garrison-permission',{allow:$('embassyAllow').checked,idempotency_key:crypto.randomUUID()})}catch(e){showNotice(e.message)}};
 document.querySelectorAll('.garrison-return').forEach(b=>b.onclick=async()=>{try{await post(`${base}/garrisons/${b.dataset.id}/return`,{idempotency_key:crypto.randomUUID()});await openEmbassy(building)}catch(e){showNotice(e.message)}});
 $('embassyAlliance').onclick=()=>openAlliance();
 const u=$('embassyUpgrade');if(u&&!u.disabled)u.onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){showNotice(e.message)}};
}
async function openCottage(building){
 const d=await get(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}`);
 const up=typeof d.upgrade==='object'?`Food ${fmt(d.upgrade.cost.food||0)} · Lumber ${fmt(d.upgrade.cost.lumber||0)} · Stone ${fmt(d.upgrade.cost.stone||0)} · Iron ${fmt(d.upgrade.cost.iron||0)} · ${duration(d.upgrade.seconds)}`:'Maximum configured level';
 $('modalBody').innerHTML=`<div class="building-panel"><h2>Cottage — Level ${d.level}</h2><div class="function-box">Population ${fmt(d.function.population)} · Idle ${fmt(d.function.idle_population)}</div><p>Cottages increase the city's population capacity.</p><h3>Upgrade</h3><p>${up}</p><button id="cottageUpgrade" class="action-btn" ${typeof d.upgrade==='object'?'':'disabled'}>Upgrade to Level ${d.level+1}</button></div>`;$('buildingModal').classList.remove('hidden');
 const u=$('cottageUpgrade');if(u&&!u.disabled)u.onclick=async()=>{try{await post(`/api/players/${state.player.id}/cities/${state.city.id}/buildings/${building.id}/upgrade`,{idempotency_key:crypto.randomUUID()});closeModal();await selectCity(state.city.id)}catch(e){showNotice(e.message)}};
}
const __uiSpecificBuilding=openBuilding;
openBuilding=async function(building){
 if(building.definition_key==='inn')return openInn(building);
 if(building.definition_key==='marketplace')return openMarketplace(building);
 if(building.definition_key==='embassy')return openEmbassy(building);
 if(building.definition_key==='cottage')return openCottage(building);
 return __uiSpecificBuilding(building)
};

async function openRallyForTarget(x,y,mission){
 const d=await get(`/api/players/${state.player.id}/cities/${state.city.id}/city-view`);
 const p=d.plots.find(p=>p.building&&p.building.definition_key==='rally_spot');
 if(!p){showNotice('Build a Rally Spot to dispatch troops.');return}
 await openRallySpot(p.building);$('marchX').value=x;$('marchY').value=y;
 const wanted=String(mission||'').toUpperCase();if([...$('marchMission').options].some(o=>o.value===wanted||o.text===wanted))$('marchMission').value=wanted;
}
const __uiOpenMapTile=openMapTile;
openMapTile=async function(x,y){
 await __uiOpenMapTile(x,y);
 document.querySelectorAll('.map-action').forEach(b=>b.onclick=async()=>{const mission=b.dataset.a==='REINFORCE'?'REINFORCE':b.dataset.a==='TRANSPORT'?'TRANSPORT':b.dataset.a==='SCOUT'?'SCOUT':b.dataset.a==='OCCUPY'?'OCCUPY':'ATTACK';closeModal();await openRallyForTarget(x,y,mission)});
};

const __uiLoadBookmarks=loadBookmarks;
loadBookmarks=async function(){await __uiLoadBookmarks();const src=$('mapBookmarks'),dst=$('railBookmarks');if(dst&&src)dst.innerHTML=src.innerHTML||'No bookmarks.';if(dst){dst.querySelectorAll('.bookmark-jump').forEach(b=>b.onclick=()=>{switchView('map');centerMap(+b.dataset.x,+b.dataset.y)});dst.querySelectorAll('.bookmark-delete').forEach(b=>b.onclick=async()=>{try{await request(`/api/players/${state.player.id}/map/bookmarks/${b.dataset.id}?idempotency_key=${encodeURIComponent(crypto.randomUUID())}`,{method:'DELETE'});await loadBookmarks()}catch(e){showNotice(e.message)}})}};

function tickVisibleTimers(){
 document.querySelectorAll('[data-deadline]').forEach(el=>{const n=Math.max(0,Math.floor((new Date(el.dataset.deadline)-Date.now())/1000));el.textContent=duration(n)})
}
setInterval(tickVisibleTimers,1000);
